### ISSUE TITLE
Incorrect world generation on server

### ISSUE THREAD

**Issue by qrxt** [DM-Earth/Cabricality-server#1]
Hello.

For some reason, some blocks are generated incorrectly. 
![server](https://user-images.githubusercontent.com/46269438/195444904-a008ee5e-4cac-4c02-b34b-8fe38825dc69.png)

Certus Quartz Ore -> ME Pattern Provider
Scoria -> Cut Scoria Wall
Crimsite -> Cut Crimsite Wall
...

The problem only happens when playing on the server, in singleplayer everything is fine.
![singleplayer](https://user-images.githubusercontent.com/46269438/195445443-0aa71e7e-7775-4f7f-977e-99f857c77075.png)

The problem happens in all worlds regardless of seed.

![more weird stuff#1](https://user-images.githubusercontent.com/46269438/195446544-abd45f42-e6c2-4f76-92e4-62a52568ed3f.png)
![more weird stuff#2](https://user-images.githubusercontent.com/46269438/195446550-2d7c01fd-b4db-4e7a-b16f-a5193c5929ce.png)

seed: -2438319822579465415

Any ideas what could be the problem? Thank you in advance

**Comment by IcedDog** [comment]
If the client and server have different versions of mod loader then this can happen
https://discord.com/channels/999146491987902484/1028874962905346058/1029883876639768606

**Comment by IcedDog** [comment]
@JieningYu uh, maybe make a check function into cabf edit?
