### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by fx46** [DM-Earth/Cabricality-server#3]
Hello, I'm getting a crash at startup after a fresh install of the 0.3 server, and also after adding the required FTB/equator/questAdditions/REI/itemFilters mods.
Here's the log file:
[latest.log](https://github.com/DM-Earth/Cabricality-Server/files/12135880/latest.log)

**Comment by JieningYu** [comment]
based

**Comment by JieningYu** [comment]
some client object supplier lambdas was converted into general expressions due to the lint by Intellij Idea. based

**Comment by leosefcik** [comment]
same here!

**Comment by JieningYu** [comment]
this should be fixed in https://github.com/DM-Earth/Cabricality/commit/732911e651949194245d2de6d02d41840d24e7e8.

please test the new-built Cabricality mod whether it will crash the server again.

**Comment by fx46** [comment]
@JieningYu Thanks! Where can I find the new-built mod?

**Comment by JieningYu** [comment]
github actions artifact

**Comment by fx46** [comment]
It worked! thanks 🥇
